PL_MVC/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();

            //Se hace el acceso al servidor ServiceProducto
            AlumnoReference1.AlumnoClient context = new AlumnoReference1.AlumnoClient();
            
            var result = context.GetAll();
            
            //ML.Result result = new ML.Result();
            //result = BL.Alumno.AlumnoGetAll();
            if (result.Correct)
            {
                alumno.Alumnos = result.Objects.ToList();
            }
            else
            {
                ViewBag.Mensaje = "No se pueden mostrar los alumnos";
            }
            return View(alumno);
        }

        public ActionResult Form (int? IdAlumno)
        {
            ML.Alumno alumno = new ML.Alumno();
            
            if(alumno == null)
            {
                return View(alumno);
            }
            else
            {

                
                //Se hace el acceso al servidor ServiceProducto
                AlumnoReference1.AlumnoClient context = new AlumnoReference1.AlumnoClient();

                var  result = context.GetById(IdAlumno.Value);
                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;
                }
                else
                {
                    ViewBag.Mensaje = "No se pueden mostrar los alumnos";
                }
                return View(alumno);

            }
        }

        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            

            if (alumno.IdAlumno == 0)
            {
                AlumnoReference1.AlumnoClient context = new AlumnoReference1.AlumnoClient();

                var result = context.Add(alumno);
                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;
                    ViewBag.Mensaje = "Usuario guardado exitosamente";

                }
                else
                {
                    ViewBag.Mensaje = "Ocurrio un error al agregar al usuario";
                }
            }
            else
            {
                //update

                AlumnoReference1.AlumnoClient context = new AlumnoReference1.AlumnoClient();
               var result = context.UpDate(alumno);

                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;
                    ViewBag.Mensaje = "Usuario Actualizado Correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "Ocurrio un error El usuario no se pudo actualizar";
                }

            }

            return PartialView("Modal");

        }
        [HttpGet]
        public ActionResult Delete(int IdAlumno)
        {
            AlumnoReference1.AlumnoClient context = new AlumnoReference1.AlumnoClient();
            var result = context.Delete(IdAlumno);
            if (result.Correct)
            {
                ViewBag.Mensaje = "Se elimino el registro";
            }
            return PartialView("Modal");
        }

    }
}

PL_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL_MVC/Controllers/MateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class MateriaController : Controller
    {
        // GET: Materia
        public ActionResult GetAll()
        {
            ML.Materia materia = new ML.Materia();

            ML.Result result = new ML.Result();
            result = BL.Materia.Getall();
            if (result.Correct)
            {
                materia.Materias = result.Objects.ToList();
            }
            else
            {
                ViewBag.Mensaje = "No se pueden mostrar los alumnos";
            }
            return View(materia);
        }

        public ActionResult Form(int? idMateria)
        {
            ML.Materia materia = new ML.Materia();

            if (materia == null)
            {
                return View(materia);
            }
            else
            {
                ML.Result result = new ML.Result();
                result = BL.Materia.GetById(idMateria.Value);
                if (result.Correct)
                {
                    materia = (ML.Materia)result.Object;
                }
                else
                {
                    ViewBag.Mensaje = "No se pueden mostrar los alumnos";
                }
                return View(materia);

            }
        }

        [HttpPost]
        public ActionResult Form(ML.Materia materia)
        {


            if (materia.idMateria == 0)
            {
                ML.Result result = new ML.Result();
                result = BL.Materia.Add(materia);
                if (result.Correct)
                {
                    materia = (ML.Materia)result.Object;
                    ViewBag.Mensaje = "Usuario guardado exitosamente";

                }
                else
                {
                    ViewBag.Mensaje = "Ocurrio un error al agregar al usuario";
                }
            }
            else
            {
                //update

                ML.Result result = new ML.Result();
                result = BL.Materia.UpDate(materia);
                if (result.Correct)
                {
                    materia = (ML.Materia)result.Object;
                    ViewBag.Mensaje = "Usuario Actualizado Correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "Ocurrio un error El usuario no se pudo actualizar";
                }

            }

            return PartialView("Modal");

        }
        [HttpGet]
        public ActionResult Delete(int idMatreria)
        {
            ML.Result result = new ML.Result();
            result = BL.Materia.Delete(idMatreria);
            if (result.Correct)
            {
                ViewBag.Mensaje = "Se elimino el registro";
            }
            return PartialView("Modal");
        }
    }
}

PL_MVC/Views/Alumno/Form.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Form</h2>
<div class=" container">
    <h2>Form</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Alumno", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdAlumno, new { @class = "hidden" })

                            @Html.TextBoxFor(model => model.IdAlumno, new { @class = "hidden form-control" })

                            @Html.ValidationMessageFor(model => model.IdAlumno)

                        </div>

                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Nombre)
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(model => model.Nombre)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.ApellidoPaterno)
                            @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(model => model.ApellidoPaterno)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.ApellidoMaterno)
                            @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(model => model.ApellidoMaterno)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-success" })
                        </div>
                    </div>


                </div>

            }
        </div>
    </div>
</div>

PL_MVC/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de alumnos</h2>
<div class="container">
    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Alumno", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>
    <div class="row">
        <table class="tablcenter table-hover table-bordered table-responsive ">

            <thead>
                <tr>
                    <th>Editar</th>
                    <th>Nombre</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Alumno alumno in Model.Alumnos)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Alumno", new { IdAlumno = alumno.IdAlumno })"></a></td>
                        <td class="hidden">@alumno.IdAlumno</td>
                        <td>@alumno.Nombre @alumno.ApellidoPaterno @alumno.ApellidoMaterno</td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Alumno", new { IdAlumno = alumno.IdAlumno })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL_MVC/Views/Materia/Form.cshtml
@model ML.Materia
@{
    ViewBag.Title = "Form";
}

<h2>Form</h2>

PL_MVC/Views/Materia/GetAll.cshtml
@model ML.Materia
@{
    ViewBag.Title = "GetAll";
}

<h2>Lista de alumnos</h2>
<div class="container">
    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Materia", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>
    <div class="row">
        <table class="tablcenter table-hover table-bordered table-responsive ">

            <thead>
                <tr>
                    <th>Editar</th>
                    <th>Nombre</th>
                    <th>Costo</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Materia materia in Model.Materias)
                {
    <tr>
        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Alumno", new { IdAlumno = alumno.IdAlumno })"></a></td>
        <td class="hidden">@alumno.IdAlumno</td>
        <td>@alumno.Nombre @alumno.ApellidoPaterno @alumno.ApellidoMaterno</td>
        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Alumno", new { IdAlumno = alumno.IdAlumno })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
    </tr>}
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Alumnos", "GetAll", "Alumno")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>